// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "jwt-signin": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/JormungandrK/jwt-issuer/design
// --out=$(GOPATH)/src/github.com/JormungandrK/jwt-issuer
// --version=v1.2.0-dirty

package app
