// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "jwt-signin": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/Microkubes/jwt-issuer/design
// --out=$(GOPATH)/src/github.com/Microkubes/jwt-issuer
// --version=v1.3.1

package app
